"""add_contact_info_to_user_profile

Revision ID: d3f409e330ef
Revises: 6e2404a7c50c
Create Date: 2026-07-14 14:19:16.674382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f409e330ef'
down_revision: Union[str, Sequence[str], None] = '6e2404a7c50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'phone')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
